// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaTc3eQPeli10s3K44gS7xysH1f6UDlkI',
    appId: '1:558180308375:web:a33ab1a1d98814d73da0d2',
    messagingSenderId: '558180308375',
    projectId: 'kiukiu-51c46',
    authDomain: 'kiukiu-51c46.firebaseapp.com',
    storageBucket: 'kiukiu-51c46.appspot.com',
    measurementId: 'G-PZXPVQ4NVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Bp8NzgyxDhs7VXWCDly1G-6S9MvrDa8',
    appId: '1:558180308375:android:6bc97f7b2de4e4da3da0d2',
    messagingSenderId: '558180308375',
    projectId: 'kiukiu-51c46',
    storageBucket: 'kiukiu-51c46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAotPn3P-ExY3K3puFE3U2TLYnmbvKaow',
    appId: '1:558180308375:ios:88498db9dff216b13da0d2',
    messagingSenderId: '558180308375',
    projectId: 'kiukiu-51c46',
    storageBucket: 'kiukiu-51c46.appspot.com',
    iosClientId: '558180308375-uq4mtvibg5lfi8a4ik2c3s3gu15t790o.apps.googleusercontent.com',
    iosBundleId: 'com.joan.samuel.weddingBackOffice',
  );
}
